apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: busy-ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-app
  labels:
    app: busy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-app
  template:
    metadata:
      labels:
        app: busy-app
    spec:
      nodeSelector:
        nodegroup: wsi-self-managed-ng
      containers:
        - name: busy-container
          image: public.ecr.aws/amazonlinux/amazonlinux
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do echo $(date -u) >> /data/out.txt; sleep 10; done",
            ]
          volumeMounts:
            - name: ebs-volume
              mountPath: /data
      volumes:
        - name: ebs-volume
          persistentVolumeClaim:
            claimName: busy-ebs-claim
